### ISSUE TITLE
FTBFS 

### ISSUE THREAD

**Issue by mcepl** [gpodder/GpodRoid#4]
Using 

java version "1.6.0_22"
OpenJDK Runtime Environment (IcedTea6 1.10.3) (fedora-59.1.10.3.fc16-x86_64)
OpenJDK 64-Bit Server VM (build 20.0-b11, mixed mode)

and freshly upgraded Android SDK. the log of ant debug is https://gist.github.com/1256459

And if I may add rant on the side: wouldn't it be more profitable for users and general friends of FLOSS if you joined forces with http://webworxshop.com/projects/swallowcatcher ? It would be awesome to have at least ONE podcatcher working than two which are mostly broken (SwallowCatcher works at least a bit)?

**Comment by nheid** [comment]
hey,
the build is missing robotium.
make sure that the jars directory is in your build/classpath.

cheers, nico

On Sat, Oct 1, 2011 at 20:29, mcepl
reply@reply.github.com
wrote:

> Using
> 
> java version "1.6.0_22"
> OpenJDK Runtime Environment (IcedTea6 1.10.3) (fedora-59.1.10.3.fc16-x86_64)
> OpenJDK 64-Bit Server VM (build 20.0-b11, mixed mode)
> 
> and freshly upgraded Android SDK. the log of ant debug is https://gist.github.com/1256459
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/gpodder/GpodRoid/issues/4

## 

Nico Heid - http://nicoheid.com - mob. +491733181059
